CREATE TABLE `scraped_company`
(
    `id`                 bigint        NOT NULL AUTO_INCREMENT,
    `keyword`            varchar(128)  NOT NULL COMMENT '搜索关键字',
    `list_url`           varchar(1024) NOT NULL COMMENT '列表页面url',
    `detail_url`         varchar(1024) NOT NULL COMMENT '详情页面url',
    `raw_logo`           varchar(1024) NOT NULL DEFAULT '' COMMENT '原始logo',
    `logo`               varchar(1024) NOT NULL DEFAULT '' COMMENT 'logo',
    `name`               varchar(256)  NOT NULL DEFAULT '' COMMENT '名称',
    `tags`               varchar(256)  NOT NULL DEFAULT '' COMMENT '标签，逗号分割',
    `industry`           varchar(128)  NOT NULL DEFAULT '' COMMENT '所属行业',
    `telephone`          varchar(32)   NOT NULL DEFAULT '' COMMENT '电话',
    `email`              varchar(128)  NOT NULL DEFAULT '' COMMENT '邮箱',
    `site`               varchar(128)  NOT NULL DEFAULT '' COMMENT '网址',
    `intro`              varchar(4096) NOT NULL DEFAULT '' COMMENT '简介',
    `open_status`        varchar(32)   NOT NULL DEFAULT '' COMMENT '经营状态',
    `main_business`      varchar(256)  NOT NULL DEFAULT '' COMMENT '主营业务',
    `business_scope`     text          NOT NULL COMMENT '经营范围',
    `ent_type`           varchar(64)   NOT NULL DEFAULT '' COMMENT '企业类型',
    `unified_code`       varchar(32)   NOT NULL DEFAULT '' COMMENT '统一社会信用代码',
    `legal_person`       varchar(32)   NOT NULL DEFAULT '' COMMENT '法定代表人',
    `reg_capital`        varchar(32)   NOT NULL DEFAULT '' COMMENT '注册资本',
    `start_date`         varchar(16)   NOT NULL DEFAULT '' COMMENT '成立日期',
    `annual_date`        varchar(16)   NOT NULL DEFAULT '' COMMENT '核准日期',
    `authority`          varchar(128)  NOT NULL DEFAULT '' COMMENT '登记机关',
    `reg_addr`           varchar(128)  NOT NULL DEFAULT '' COMMENT '注册地址',
    `personnel_scale`    varchar(32)   NOT NULL DEFAULT '' COMMENT '人员规模',
    `org_code`           varchar(32)   NOT NULL DEFAULT '' COMMENT '组织机构代码',
    `business_reg_no`    varchar(32)   NOT NULL DEFAULT '' COMMENT '工商注册号',
    `subordinate_region` varchar(128)  NOT NULL DEFAULT '' COMMENT '所属地区',
    `work_time`          varchar(64)   NOT NULL DEFAULT '' COMMENT '上下班时间',
    `ext_fields`         json COMMENT '扩展字段',
    `scrape_channel`     varchar(32)   NOT NULL COMMENT '爬取渠道',
    `created_at`         datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP (3),
    PRIMARY KEY (`id`),
    KEY                  `idx_keyword` (`keyword`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci COMMENT ='已爬取公司信息';
